# Generated by Django 2.0.2 on 2018-02-21 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('caption', models.CharField(max_length=128)),
                ('template', models.CharField(max_length=64)),
                ('infoText', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DBAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('infoText', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255)),
                ('infoText', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationHasOrganizationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization')),
                ('organizationCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.OrganizationCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('ACT', 'Active'), ('SUS', 'Suspended'), ('DEL', 'Deleted')], max_length=5)),
                ('infoText', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=512)),
                ('infoText', models.CharField(blank=True, max_length=255, null=True)),
                ('contactType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ContactType')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Party')),
            ],
        ),
        migrations.CreateModel(
            name='PartyHasRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infoText', models.CharField(blank=True, max_length=255, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Party')),
            ],
        ),
        migrations.CreateModel(
            name='PartyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('caption', models.CharField(max_length=60)),
                ('infoText', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=128)),
                ('issueAuth', models.CharField(max_length=255)),
                ('infoText', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PassportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=45)),
                ('infoText', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(max_length=100)),
                ('endDate', models.DateField(max_length=100)),
                ('firstName', models.CharField(max_length=45)),
                ('secondName', models.CharField(max_length=45)),
                ('patronymicName', models.CharField(max_length=45)),
                ('birthDate', models.DateField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('taxCode', models.CharField(max_length=18)),
                ('infoText', models.CharField(blank=True, max_length=255, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Party')),
            ],
        ),
        migrations.CreateModel(
            name='PersonCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=128)),
                ('infoText', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonHasPersonCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infoText', models.CharField(blank=True, max_length=255, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Person')),
                ('personCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PersonCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=64)),
                ('destPartyHasRole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destPartyHasRole', to='core.PartyHasRole')),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=64)),
                ('srcDef', models.CharField(max_length=45)),
                ('dstDef', models.CharField(max_length=45)),
                ('infoText', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=128)),
                ('roleFlag', models.CharField(max_length=8)),
                ('infoText', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='relationship',
            name='relationshipType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.RelationshipType'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='srcPartyHasRole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srcPartyHasRole', to='core.PartyHasRole'),
        ),
        migrations.AddField(
            model_name='passport',
            name='passportType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PassportType'),
        ),
        migrations.AddField(
            model_name='passport',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Person'),
        ),
        migrations.AddField(
            model_name='partyhasrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Role'),
        ),
        migrations.AddField(
            model_name='party',
            name='partyType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PartyType'),
        ),
        migrations.AddField(
            model_name='organization',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Party'),
        ),
    ]
